### PR TITLE
Add `battery-level` and `screensaver`

### PR DESCRIPTION
**Pull request by gillstrom**
If you want me to place `screensaver` under `Screensavers` I can move it.

### CODE REVIEW

**Comment by aharris88** [comment]
Looks pretty cool. I'm checking out the tools and I put in a few issues on them. I just want to start making sure that everything on the list is really awesome.

**Comment by gillstrom** [comment]
I could remove `vol` from this to get this merged?

**Comment by aharris88** [comment]
Yeah, absolutely. And if I can ever get vol to work on my computer, I'll let you know.

**Comment by gillstrom** [comment]
Fixed, should now only include `battery-level` and `screensaver`.

**Pull request merged**
